-- Generated by AppNow database automation.
-- Review before running in Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists "users" (
  id text primary key default gen_random_uuid()::text,
  "legacy_user_id" integer,
  "name" text,
  "phone" text,
  "email" text,
  "password_hash" text,
  "address" text,
  "address_detail" text,
  "provider" text,
  "is_guest" boolean,
  "is_admin" boolean,
  "email_verified" boolean,
  "kakao_id" text,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  "migrated_at" timestamptz,
  "migration_source" text
);

create index if not exists "users_migration_source_idx"
  on "users" (migration_source);

create unique index if not exists "users_email_unique_idx"
  on "users" (lower(email))
  where email is not null;

create table if not exists "bookings" (
  id text primary key default gen_random_uuid()::text,
  "user_id" text,
  "legacy_user_id" integer,
  "asset_id" text,
  "name" text,
  "phone" text,
  "address" text,
  "detail_address" text,
  "is_guest" boolean,
  "subtype" text,
  "service_type" text,
  "reservation_date" text,
  "reservation_time" text,
  "options" jsonb,
  "tier" text,
  "memo" text,
  "symptom" text,
  "status" text,
  "total_price" integer,
  "created_at" timestamptz,
  "migrated_at" timestamptz,
  "migration_source" text
);

create index if not exists "bookings_migration_source_idx"
  on "bookings" (migration_source);

-- AppNow reusable backend core.

create table if not exists "audit_logs" (
  id uuid primary key default gen_random_uuid(),
  actor_id text,
  table_name text not null,
  row_id text not null,
  action text not null,
  patch jsonb,
  created_at timestamptz not null default now()
);

create index if not exists "audit_logs_table_row_idx"
  on "audit_logs" (table_name, row_id);

create table if not exists "catalog_categories" (
  id text primary key,
  key text unique not null,
  label text not null,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  migrated_at timestamptz,
  migration_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists "service_types" (
  id text primary key,
  category_id text references "catalog_categories"(id) on delete set null,
  key text unique not null,
  label text not null,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  migrated_at timestamptz,
  migration_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists "pricing_tiers" (
  id text primary key,
  service_type_id text references "service_types"(id) on delete cascade,
  service_type text,
  subtype text,
  key text not null,
  label text not null,
  base_price integer not null default 0,
  sort_order integer not null default 0,
  memo text,
  metadata jsonb not null default '{}'::jsonb,
  migrated_at timestamptz,
  migration_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists "request_options" (
  id text primary key,
  service_type_id text references "service_types"(id) on delete cascade,
  key text not null,
  label text not null,
  extra_cost integer not null default 0,
  applies_to jsonb not null default '[]'::jsonb,
  choices jsonb not null default '[]'::jsonb,
  service_types jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  migrated_at timestamptz,
  migration_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists "subtypes" (
  id text primary key,
  key text unique not null,
  label text not null,
  category text,
  icon_url text,
  service_options jsonb not null default '[]'::jsonb,
  migrated_at timestamptz,
  migration_source text
);

create table if not exists "assets" (
  id text primary key,
  service_type text,
  kind text,
  tier text,
  part_id text,
  subtype text,
  label text,
  steps jsonb not null default '[]'::jsonb,
  url text,
  migrated_at timestamptz,
  migration_source text
);

create table if not exists "timeslots" (
  id text primary key,
  date date,
  type text,
  slots jsonb not null default '[]'::jsonb,
  migrated_at timestamptz,
  migration_source text
);

create table if not exists "counters" (
  id text primary key,
  name text,
  sequence bigint not null default 0,
  migrated_at timestamptz,
  migration_source text
);

create table if not exists "requests" (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  legacy_user_id integer,
  category_id text,
  service_type_id text,
  subtype_id text,
  pricing_tier_id text,
  option_ids jsonb not null default '[]'::jsonb,
  name text not null,
  phone text,
  address text,
  detail_address text,
  symptom text,
  memo text,
  reservation_date date not null,
  reservation_time text not null,
  timezone text not null default 'Asia/Seoul',
  status text not null default 'pending',
  total_price integer not null default 0,
  legacy_id text,
  migration_source text,
  migrated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists "requests_unique_active_slot_idx"
  on "requests" (reservation_date, reservation_time)
  where status in ('pending', 'confirmed', 'approved');

create index if not exists "requests_user_history_idx"
  on "requests" (user_id, reservation_date desc);

create index if not exists "requests_status_date_idx"
  on "requests" (status, reservation_date);

create table if not exists "app_drafts" (
  id uuid primary key default gen_random_uuid(),
  owner_id text not null,
  app_name text not null,
  template_id text not null,
  market text not null,
  platform text not null check (platform in ('web', 'mobile', 'both')),
  language_mode text not null check (language_mode in ('en-first-ko-ready', 'en-only', 'ko-first')),
  ai_provider text not null default 'openai',
  source text not null,
  status text not null default 'draft' check (status in ('draft', 'pending')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists "app_drafts_owner_created_idx"
  on "app_drafts" (owner_id, created_at desc);
