-- Generated by AppNow database automation.
-- Starter RLS policies. Review before production use.

alter table "users" enable row level security;

drop policy if exists "users_service_role_all" on "users";
create policy "users_service_role_all"
  on "users"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "bookings" enable row level security;

drop policy if exists "bookings_service_role_all" on "bookings";
create policy "bookings_service_role_all"
  on "bookings"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "audit_logs" enable row level security;

drop policy if exists "audit_logs_service_role_all" on "audit_logs";
create policy "audit_logs_service_role_all"
  on "audit_logs"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "catalog_categories" enable row level security;

drop policy if exists "catalog_categories_service_role_all" on "catalog_categories";
create policy "catalog_categories_service_role_all"
  on "catalog_categories"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "service_types" enable row level security;

drop policy if exists "service_types_service_role_all" on "service_types";
create policy "service_types_service_role_all"
  on "service_types"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "pricing_tiers" enable row level security;

drop policy if exists "pricing_tiers_service_role_all" on "pricing_tiers";
create policy "pricing_tiers_service_role_all"
  on "pricing_tiers"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "request_options" enable row level security;

drop policy if exists "request_options_service_role_all" on "request_options";
create policy "request_options_service_role_all"
  on "request_options"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "subtypes" enable row level security;

drop policy if exists "subtypes_service_role_all" on "subtypes";
create policy "subtypes_service_role_all"
  on "subtypes"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "assets" enable row level security;

drop policy if exists "assets_service_role_all" on "assets";
create policy "assets_service_role_all"
  on "assets"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "timeslots" enable row level security;

drop policy if exists "timeslots_service_role_all" on "timeslots";
create policy "timeslots_service_role_all"
  on "timeslots"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "counters" enable row level security;

drop policy if exists "counters_service_role_all" on "counters";
create policy "counters_service_role_all"
  on "counters"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "requests" enable row level security;

drop policy if exists "requests_service_role_all" on "requests";
create policy "requests_service_role_all"
  on "requests"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

alter table "app_drafts" enable row level security;

drop policy if exists "app_drafts_service_role_all" on "app_drafts";
create policy "app_drafts_service_role_all"
  on "app_drafts"
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
