-- Private customer-supplied photos and videos attached to canonical bookings.
--
-- Binary objects live in Supabase Storage. This table is the authoritative
-- ownership and lifecycle record; signed upload/download capabilities are
-- generated by the API and are never persisted here.

create unique index if not exists bookings_id_user_id_unique_idx
  on public.bookings (id, user_id);

create table if not exists public.booking_attachments (
  id uuid primary key default gen_random_uuid(),
  client_attachment_id uuid not null,
  booking_id text not null,
  owner_user_id text not null,
  bucket_id text not null,
  object_path text not null,
  media_kind text not null,
  mime_type text not null,
  declared_size_bytes bigint not null,
  actual_size_bytes bigint,
  status text not null default 'pending',
  storage_etag text,
  upload_expires_at timestamptz not null,
  write_expires_at timestamptz not null,
  completed_at timestamptz,
  failure_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_attachments_booking_owner_fkey
    foreign key (booking_id, owner_user_id)
    references public.bookings (id, user_id)
    on delete restrict,
  constraint booking_attachments_client_id_unique
    unique (booking_id, client_attachment_id),
  constraint booking_attachments_storage_object_unique
    unique (bucket_id, object_path),
  constraint booking_attachments_status_check
    check (status in ('pending', 'ready', 'deleting', 'rejected')),
  constraint booking_attachments_kind_bucket_check
    check (
      (media_kind = 'image' and bucket_id = 'shc-booking-images-v1')
      or
      (media_kind = 'video' and bucket_id = 'shc-booking-videos-v1')
    ),
  constraint booking_attachments_mime_check
    check (
      (media_kind = 'image' and mime_type in ('image/jpeg', 'image/png', 'image/webp'))
      or
      (media_kind = 'video' and mime_type in ('video/mp4', 'video/quicktime'))
    ),
  constraint booking_attachments_declared_size_check
    check (
      (media_kind = 'image' and declared_size_bytes between 1 and 10000000)
      or
      (media_kind = 'video' and declared_size_bytes between 1 and 45000000)
    ),
  constraint booking_attachments_actual_size_check
    check (actual_size_bytes is null or actual_size_bytes = declared_size_bytes),
  constraint booking_attachments_path_check
    check (object_path ~ '^v1/[0-9a-f]{2}/[0-9a-f-]{36}\.(jpg|png|webp|mp4|mov)$')
);

create index if not exists booking_attachments_booking_status_created_idx
  on public.booking_attachments (booking_id, status, created_at);

create index if not exists booking_attachments_owner_created_idx
  on public.booking_attachments (owner_user_id, created_at desc);

create index if not exists booking_attachments_pending_expiry_idx
  on public.booking_attachments (write_expires_at)
  where status = 'pending';

-- Operational circuit breaker for a public launch. Raise these values only
-- after confirming the provider quota, billing alerts, retention job, and
-- observed object-size distribution. This table is intentionally not part of
-- generic admin CRUD.
create table if not exists public.booking_media_limits (
  singleton_key text primary key default 'default',
  max_reserved_rows integer not null default 100,
  max_reserved_bytes bigint not null default 500000000,
  updated_at timestamptz not null default now(),
  constraint booking_media_limits_singleton_check
    check (singleton_key = 'default'),
  constraint booking_media_limits_rows_check
    check (max_reserved_rows between 1 and 1000000),
  constraint booking_media_limits_bytes_check
    check (max_reserved_bytes between 1 and 1000000000000)
);

insert into public.booking_media_limits (
  singleton_key, max_reserved_rows, max_reserved_bytes
)
values ('default', 100, 500000000)
on conflict (singleton_key) do nothing;

drop trigger if exists booking_media_limits_touch_updated_at on public.booking_media_limits;
create trigger booking_media_limits_touch_updated_at
before update on public.booking_media_limits
for each row execute function public.touch_updated_at();

create or replace function public.enforce_booking_attachment_limits()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  existing_count integer;
  existing_video_count integer;
  existing_total_bytes bigint;
  owner_reserved_count integer;
  owner_reserved_bytes bigint;
  project_reserved_count integer;
  project_reserved_bytes bigint;
  project_max_rows integer;
  project_max_bytes bigint;
begin
  perform pg_advisory_xact_lock(
    hashtextextended('booking-media-project', 0)
  );
  perform pg_advisory_xact_lock(
    hashtextextended('booking-media-owner:' || new.owner_user_id, 0)
  );
  perform pg_advisory_xact_lock(
    hashtextextended('booking-attachments:' || new.booking_id, 0)
  );

  select max_reserved_rows, max_reserved_bytes
  into project_max_rows, project_max_bytes
  from public.booking_media_limits
  where singleton_key = 'default';

  if not found then
    raise exception 'PROJECT_MEDIA_LIMIT_REACHED: project media limit configuration is missing'
      using errcode = '23514';
  end if;

  select
    count(*)::integer,
    coalesce(sum(declared_size_bytes), 0)::bigint
  into project_reserved_count, project_reserved_bytes
  from public.booking_attachments
  where id <> new.id;

  if project_reserved_count >= project_max_rows
     or project_reserved_bytes + new.declared_size_bytes > project_max_bytes then
    raise exception 'PROJECT_MEDIA_LIMIT_REACHED: project media reservations reached the configured ceiling'
      using errcode = '23514';
  end if;

  select
    count(*)::integer,
    coalesce(sum(declared_size_bytes), 0)::bigint
  into owner_reserved_count, owner_reserved_bytes
  from public.booking_attachments
  where owner_user_id = new.owner_user_id
    and id <> new.id;

  if owner_reserved_count >= 12
     or owner_reserved_bytes + new.declared_size_bytes > 100000000 then
    raise exception 'USER_MEDIA_LIMIT_REACHED: owner can reserve at most 12 rows and 100000000 bytes'
      using errcode = '23514';
  end if;

  select
    count(*)::integer,
    count(*) filter (where media_kind = 'video')::integer,
    coalesce(sum(declared_size_bytes), 0)::bigint
  into existing_count, existing_video_count, existing_total_bytes
  from public.booking_attachments
  where booking_id = new.booking_id
    and id <> new.id;

  if existing_count >= 6 then
    raise exception 'A booking can have at most 6 attachments'
      using errcode = '23514';
  end if;

  if new.media_kind = 'video' and existing_video_count >= 2 then
    raise exception 'A booking can have at most 2 video attachments'
      using errcode = '23514';
  end if;

  if existing_total_bytes + new.declared_size_bytes > 100000000 then
    raise exception 'Booking attachments can total at most 100000000 bytes'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists booking_attachments_enforce_limits on public.booking_attachments;
create trigger booking_attachments_enforce_limits
before insert or update of booking_id, owner_user_id, media_kind, declared_size_bytes
on public.booking_attachments
for each row execute function public.enforce_booking_attachment_limits();

drop trigger if exists booking_attachments_touch_updated_at on public.booking_attachments;
create trigger booking_attachments_touch_updated_at
before update on public.booking_attachments
for each row execute function public.touch_updated_at();

alter table public.booking_attachments enable row level security;
alter table public.booking_media_limits enable row level security;

revoke all on table public.booking_attachments from anon, authenticated;
grant all on table public.booking_attachments to service_role;
revoke all on table public.booking_media_limits from anon, authenticated;
grant all on table public.booking_media_limits to service_role;

drop policy if exists booking_attachments_service_role_all on public.booking_attachments;
create policy booking_attachments_service_role_all
  on public.booking_attachments
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists booking_media_limits_service_role_all on public.booking_media_limits;
create policy booking_media_limits_service_role_all
  on public.booking_media_limits
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- A private bucket flag is not an authorization boundary if this Supabase
-- project already has a broad authenticated storage.objects policy. This
-- restrictive guard makes both booking-media buckets inaccessible through
-- ordinary anon/authenticated Storage APIs even when another permissive policy
-- matches. Backend service-role operations and path-bound signed capabilities
-- continue to use Supabase's privileged/signed paths.
drop policy if exists shc_booking_media_deny_direct_client_access on storage.objects;
create policy shc_booking_media_deny_direct_client_access
  on storage.objects
  as restrictive
  for all
  to anon, authenticated
  using (bucket_id not in ('shc-booking-images-v1', 'shc-booking-videos-v1'))
  with check (bucket_id not in ('shc-booking-images-v1', 'shc-booking-videos-v1'));

-- Creating an attachment or publishing pending -> ready is serialized with
-- booking cancellation/completion by locking the canonical booking row. Other
-- state transitions (admin purge, account erasure, rejection, reconciliation)
-- remain allowed after the booking becomes non-editable.
create or replace function public.enforce_booking_attachment_editable_state()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' or (new.status = 'ready' and old.status is distinct from 'ready') then
    perform 1
    from public.bookings
    where id = new.booking_id
      and user_id = new.owner_user_id
      and status in ('대기', '확정', 'pending', 'confirmed', 'approved')
    for update;

    if not found then
      raise exception 'BOOKING_MEDIA_LOCKED: booking is not editable'
        using errcode = '23514',
              constraint = 'booking_attachments_booking_editable_check';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists booking_attachments_enforce_editable_state on public.booking_attachments;
create trigger booking_attachments_enforce_editable_state
before insert or update of status
on public.booking_attachments
for each row execute function public.enforce_booking_attachment_editable_state();

-- Refresh is monotonic and uses database wall-clock time. A concurrent
-- completion may change pending -> ready, in which case this returns no row and
-- the API must not mint a new Storage capability.
create or replace function public.refresh_booking_attachment_capability(
  p_attachment_id uuid
)
returns setof public.booking_attachments
language plpgsql
volatile
set search_path = public, pg_temp
as $$
declare
  target public.booking_attachments%rowtype;
begin
  select attachments.*
  into target
  from public.booking_attachments attachments
  where attachments.id = p_attachment_id
  for update;

  if not found or target.status <> 'pending' then
    return;
  end if;

  perform 1
  from public.bookings
  where id = target.booking_id
    and user_id = target.owner_user_id
    and status in ('대기', '확정', 'pending', 'confirmed', 'approved')
  for update;

  if not found then
    raise exception 'BOOKING_MEDIA_LOCKED: booking is not editable'
      using errcode = '23514',
            constraint = 'booking_attachments_booking_editable_check';
  end if;

  return query
  update public.booking_attachments attachments
  set
    upload_expires_at = greatest(
      attachments.upload_expires_at,
      clock_timestamp() + interval '2 hours'
    ),
    write_expires_at = greatest(
      attachments.write_expires_at,
      clock_timestamp() + interval '26 hours 5 minutes'
    ),
    failure_code = null
  where attachments.id = p_attachment_id
    and attachments.status = 'pending'
  returning attachments.*;
end;
$$;

-- Customer deletion has a stricter policy than administrative purge/account
-- erasure. Lock attachment then booking (the same ordering as completion) and
-- allow the transition only while the owner booking remains editable.
create or replace function public.claim_owned_booking_attachment_deletion(
  p_attachment_id uuid,
  p_owner_user_id text
)
returns setof public.booking_attachments
language plpgsql
volatile
set search_path = public, pg_temp
as $$
declare
  target public.booking_attachments%rowtype;
begin
  select attachments.*
  into target
  from public.booking_attachments attachments
  where attachments.id = p_attachment_id
    and attachments.owner_user_id = p_owner_user_id
  for update;

  if not found then
    return;
  end if;

  perform 1
  from public.bookings
  where id = target.booking_id
    and user_id = p_owner_user_id
    and status in ('대기', '확정', 'pending', 'confirmed', 'approved')
  for update;

  if not found then
    raise exception 'BOOKING_MEDIA_LOCKED: booking is not editable'
      using errcode = '23514',
            constraint = 'booking_attachments_booking_editable_check';
  end if;

  return query
  update public.booking_attachments attachments
  set status = 'deleting', failure_code = null
  where attachments.id = p_attachment_id
    and attachments.owner_user_id = p_owner_user_id
    and attachments.status in ('pending', 'ready', 'rejected', 'deleting')
  returning attachments.*;
end;
$$;

-- Reconciliation must claim the exact expired version it observed. If a retry
-- extended the capability first, or another worker changed the status, this
-- returns no row and cleanup skips it.
create or replace function public.claim_expired_booking_attachment(
  p_attachment_id uuid,
  p_observed_write_expires_at timestamptz
)
returns setof public.booking_attachments
language sql
volatile
set search_path = public
as $$
  update public.booking_attachments
  set status = 'deleting', failure_code = null
  where id = p_attachment_id
    and status = 'pending'
    and write_expires_at = p_observed_write_expires_at
    and write_expires_at <= clock_timestamp()
  returning *;
$$;

-- A final metadata delete is safe only after Storage removal, while the row is
-- still the same claimed tombstone, and after PostgreSQL says its write window
-- has closed. This prevents stale application decisions from deleting a row
-- whose capability was concurrently extended.
create or replace function public.delete_expired_booking_attachment(
  p_attachment_id uuid,
  p_observed_write_expires_at timestamptz
)
returns boolean
language sql
volatile
set search_path = public
as $$
  with deleted as (
    delete from public.booking_attachments
    where id = p_attachment_id
      and status = 'deleting'
      and write_expires_at = p_observed_write_expires_at
      and write_expires_at <= clock_timestamp()
    returning 1
  )
  select exists(select 1 from deleted);
$$;

revoke all on function public.enforce_booking_attachment_limits() from public, anon, authenticated;
grant execute on function public.enforce_booking_attachment_limits() to service_role;
revoke all on function public.enforce_booking_attachment_editable_state() from public, anon, authenticated;
grant execute on function public.enforce_booking_attachment_editable_state() to service_role;
revoke all on function public.refresh_booking_attachment_capability(uuid) from public, anon, authenticated;
grant execute on function public.refresh_booking_attachment_capability(uuid) to service_role;
revoke all on function public.claim_owned_booking_attachment_deletion(uuid, text) from public, anon, authenticated;
grant execute on function public.claim_owned_booking_attachment_deletion(uuid, text) to service_role;
revoke all on function public.claim_expired_booking_attachment(uuid, timestamptz) from public, anon, authenticated;
grant execute on function public.claim_expired_booking_attachment(uuid, timestamptz) to service_role;
revoke all on function public.delete_expired_booking_attachment(uuid, timestamptz) from public, anon, authenticated;
grant execute on function public.delete_expired_booking_attachment(uuid, timestamptz) to service_role;
